/* IVT
 * @Project : hisnguonmo
 * Copyright (C) 2017 INVENTEC
 *  
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACS.EFMODEL.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACS_ACTIVITY_LOG> ACS_ACTIVITY_LOG { get; set; }
        public DbSet<ACS_ACTIVITY_TYPE> ACS_ACTIVITY_TYPE { get; set; }
        public DbSet<ACS_APP_OTP_TYPE> ACS_APP_OTP_TYPE { get; set; }
        public DbSet<ACS_APPLICATION> ACS_APPLICATION { get; set; }
        public DbSet<ACS_APPLICATION_ROLE> ACS_APPLICATION_ROLE { get; set; }
        public DbSet<ACS_AUTHEN_REQUEST> ACS_AUTHEN_REQUEST { get; set; }
        public DbSet<ACS_AUTHOR_SYSTEM> ACS_AUTHOR_SYSTEM { get; set; }
        public DbSet<ACS_CONTROL> ACS_CONTROL { get; set; }
        public DbSet<ACS_CONTROL_ROLE> ACS_CONTROL_ROLE { get; set; }
        public DbSet<ACS_CREDENTIAL_DATA> ACS_CREDENTIAL_DATA { get; set; }
        public DbSet<ACS_MODULE> ACS_MODULE { get; set; }
        public DbSet<ACS_MODULE_GROUP> ACS_MODULE_GROUP { get; set; }
        public DbSet<ACS_MODULE_ROLE> ACS_MODULE_ROLE { get; set; }
        public DbSet<ACS_OTP> ACS_OTP { get; set; }
        public DbSet<ACS_OTP_TYPE> ACS_OTP_TYPE { get; set; }
        public DbSet<ACS_ROLE> ACS_ROLE { get; set; }
        public DbSet<ACS_ROLE_AUTHOR> ACS_ROLE_AUTHOR { get; set; }
        public DbSet<ACS_ROLE_BASE> ACS_ROLE_BASE { get; set; }
        public DbSet<ACS_ROLE_USER> ACS_ROLE_USER { get; set; }
        public DbSet<ACS_TOKEN> ACS_TOKEN { get; set; }
        public DbSet<ACS_USER> ACS_USER { get; set; }
        public DbSet<V_ACS_APPLICATION_ROLE> V_ACS_APPLICATION_ROLE { get; set; }
        public DbSet<V_ACS_CONTROL> V_ACS_CONTROL { get; set; }
        public DbSet<V_ACS_CONTROL_ROLE> V_ACS_CONTROL_ROLE { get; set; }
        public DbSet<V_ACS_MODULE> V_ACS_MODULE { get; set; }
        public DbSet<V_ACS_MODULE_ROLE> V_ACS_MODULE_ROLE { get; set; }
        public DbSet<V_ACS_ROLE_BASE> V_ACS_ROLE_BASE { get; set; }
        public DbSet<V_ACS_ROLE_USER> V_ACS_ROLE_USER { get; set; }
    }
}
