/* IVT
 * @Project : hisnguonmo
 * Copyright (C) 2017 INVENTEC
 *  
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAR.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAR_REPORT_CALENDAR
    {
        public SAR_REPORT_CALENDAR()
        {
            this.SAR_REPORT_CALENDAR1 = new HashSet<SAR_REPORT_CALENDAR>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string REPORT_CALENDAR_CODE { get; set; }
        public Nullable<short> IS_DAY_REPEAT { get; set; }
        public Nullable<short> IS_WEEK_REPEAT { get; set; }
        public Nullable<short> IS_MONTH_REPEAT { get; set; }
        public long EXECUTE_TIME { get; set; }
        public Nullable<long> END_TIME { get; set; }
        public Nullable<short> IS_DONE { get; set; }
        public string FILTER_TOTAL_JSON { get; set; }
        public Nullable<long> REPORT_ID { get; set; }
        public Nullable<long> SOURCE_ID { get; set; }
    
        public virtual SAR_REPORT SAR_REPORT { get; set; }
        public virtual ICollection<SAR_REPORT_CALENDAR> SAR_REPORT_CALENDAR1 { get; set; }
        public virtual SAR_REPORT_CALENDAR SAR_REPORT_CALENDAR2 { get; set; }
    }
}
